### ISSUE TITLE
Perplexity API doesn't work

### ISSUE THREAD

**Issue by anjor** [instructor-ai/instructor#1005]
- [x] This is actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [ ] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [x] Other (please specify)
pplx-70b-chat

**Describe the bug**
Using the Perplexity API throws a 400:
```
openai.BadRequestError: Error code: 400 - {'error': {'message': '["At body -> response_format -> ResponseFormatText -> type: Input should be \'text\'", "At body -> response_format -> ResponseFormatJSONSchema -> type: Input should be \'json_schema\'", "At body -> response_format -> ResponseFormatJSONSchema -> json_schema: Field required", "At body -> response_format -> ResponseFormatRegex -> type: Input should be \'regex\'", "At body -> response_format -> ResponseFormatRegex -> regex: Field required"]', 'type': 'bad_request', 'code': 400}}
```

**To Reproduce**

Run the example script from the repo: https://github.com/jxnl/instructor/blob/main/examples/open_source_examples/perplexity.py

**Expected behavior**
The script should run successfully.

**Comment by jxnl** [comment]
This is a known issue, perplexity does not do structured outputs well

**Comment by rooterkyberian** [comment]
It does support them, but with json schema https://docs.perplexity.ai/guides/structured-outputs#1-get-a-response-in-json-format; which seems to be related to #909
