### ISSUE TITLE
Implemennt the anthropic batch api in batch.py

### ISSUE THREAD

**Issue by jxnl** [instructor-ai/instructor#1063]
https://www.anthropic.com/news/message-batches-api 

The batch API is now available in Anthropic. I would be interested in someone helping out and being able to support this.

**Comment by josca42** [comment]
I can create a pr for this and help maintain it. Since I need this functionality in my project, where I use instructor quite a lot.

If no in else is chiming in today. I'll look into it and hopefully submit a pr tomorrow.

**Comment by josca42** [comment]
Created pr here: https://github.com/instructor-ai/instructor/pull/1075

Arrhh, just saw you created a pull request 3 days ago.. Shoot... Hmm, ok.. I guess that's it then.

Thanks for creating the library it s really useful.

**Comment by jxnl** [comment]
this is my fault for not tagging :(

**Comment by economy** [comment]
Not sure if this is working yet, on create-from-file getting: 

`BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'requests.0.params: Field required'}}`

Am I missing something? Happy to help improve this if needed

**Comment by mdabir1203** [comment]
is this done ? If it is how it is done ?

**Comment by jxnl** [comment]
https://python.useinstructor.com/cli/batch/?h=batch
