### ISSUE TITLE
LLM retry timeout - causes hanging

### ISSUE THREAD

**Issue by analyst3dev** [instructor-ai/instructor#1082]
- [ ] This is actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [ x] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [ x] Other (Azure Open AI Service GPT-4o)

**Describe the bug**
Calling instructor client for chat completion sometimes results in response taking a long time (>1m) before printing "Retrying request to /chat/completions in x secs" likely due to Azure service not responding. However, there doesn't seem to be a way to specify a timeout limit and start retry sooner. 

**To Reproduce**
```
        llm_params = {
            "model": "model name",  
            "temperature": 0,
            "frequency_penalty": 0,
            "presence_penalty": 0,
            "top_p": 1,
            "max_retries" : 2      
        }

        model = instructor_client.chat.completions.create(
            **llm_params,
            messages=[
                    # {"role": "system", "content": "You are a seasoned investment banking analyst."},
                    {"role": "user", "content": prompt}
                ],
            response_model=response_model
        )
```

**Expected behavior**
Ability to specify a timeout so the retry can happen sooner or be able to capture the exception.

**Comment by ivanbelenky** [comment]
Clients usually have a timeout keyword on their `create` calls. `openai` for instance has it. You can always check for that on instances of the native client

```python
>>> import openai
>>> client = openai.OpenAI(api_key='...')
>>> help(client.chat.completions.create)
```

I am unaware about how Azure wraps the OpenAI client for its service. I bet that they are not eliminating control over timeouts.

I would suggest checking if this is the case by forcing the timeout to happen. The following snippet works with an instructor client that was defined as `client = instructor.from_openai(OpenAI())`

```python
model = instructor_client.chat.completions.create(
    **llm_params,
    messages=[
        # {"role": "system", "content": "You are a seasoned investment banking analyst."},
        {"role": "user", "content": prompt}
    ],
    response_model=response_model,
    # add this arg to force timeout
    timeout=0.05,
)
```

**Comment by analyst3dev** [comment]
Thanks for the pointer!
Unfortunately Azure does not seem to provide to a way to control timeouts. 
https://learn.microsoft.com/en-us/azure/ai-services/openai/reference
Perhaps need to then remove max_retries from instructor and manage timeouts externally?

**Comment by ivanbelenky** [comment]
Oh wow. It is surprising that they are removing timeout in their OpenAI REST API. 

Maybe you can leverage from OpenAI client for Azure [here](https://github.com/openai/openai-python/blob/main/src/openai/lib/azure.py#L67)

If I were you I would avoid the hustle of  setting up something like
- making your `Instructor` calls async
- create a tracker to calculate `time_since_request`
- killing I/O coroutines based on timeout config

I would suggest the easy and non redundant way of decoupling the completion task and delegating it to native openai `AzureOpenAI` client, and then just recouple those completions to whatever you are building with Azure's service.

**Comment by analyst3dev** [comment]
Will try it out! Thank you.
