### ISSUE TITLE
Support for PEP 585, typing with standard collections

### ISSUE THREAD

**Issue by eliorc** [instructor-ai/instructor#1086]
**Is your feature request related to a problem? Please describe.**
At the moment, if one wishes to create a list of structured models, the approach would be

```python
from typing import List

structured_response = client.chat.completions.create(..., response_model=List[MyModel], ...)
```
which works as expected, but per [PEP585](https://peps.python.org/pep-0585/) and Python 3.9 it is now possilbe to use typing with standard collections, e.g. `List[MyModel] == list[MyModel]`. At the moment, `instructor` does not support this case, if you intent to do that, you'll get the error

>   File ".../.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-10-99f3334a785a>", line 11, in <module>
>     structured_responses[expert_name] = llm.completion(messages=structure_response_messages_,
>   File ".../llm.py", line 29, in completion
>     return instructor.from_litellm(litellm.completion).chat.completions.create(*args, response_model=response_model,
>   File ".../.venv/lib/python3.10/site-packages/instructor/client.py", line 116, in create
>     return self.create_fn(
>   File ".../.venv/lib/python3.10/site-packages/instructor/patch.py", line 140, in new_create_sync
>     response_model, new_kwargs = handle_response_model(
>   File ".../.venv/lib/python3.10/site-packages/instructor/process_response.py", line 226, in handle_response_model
>     if not issubclass(response_model, OpenAISchema):
>   File "/usr/local/lib/python3.10/abc.py", line 123, in __subclasscheck__
>     return _abc_subclasscheck(cls, subclass)
> TypeError: issubclass() arg 1 must be a class

**Describe the solution you'd like**
Support for generic-collections type hints, e.g. to be able to call

```python
structured_response = client.chat.completions.create(..., response_model=list[MyModel], ...)  # note the L is lowercase, list[MyModel]
```

**Comment by ivanbelenky** [comment]
Your above code works perfectly fine.

```python
class User(BaseModel):
    name: str
    last_name: str

users = client.chat.completions.create(
    model="gpt-4-turbo-preview",
    messages=[
        {"role": "user", "content": "Create users"},
    ],
    response_model=list[User],
)

# print(users)
# [MyModel(name='John', last_name='Doe'),
# MyModel(name='Jane', last_name='Smith'),
# MyModel(name='Emily', last_name='Jones'),
# MyModel(name='Michael', last_name='Brown')]
```

- how did you define your model? 
- what version of instructor raises this issue?

**Comment by eliorc** [comment]
@ivanbelenky my response model is a bit more complicated, I thought I'd create a simple example but I guess the simple case does work if you tried it (I haven't)

In my use case, I have an LLM that generates objects iteratively, in batches of 5. The LLM decides when to stop by itself.
For iterative generation capabilities, I created the following utility code

```python
class StopObjectCreation(BaseModel):
    """End the conversation, no more objects to create"""
    stop: bool = Field(..., description="No more objects to create")


def create_object_or_stop(obj: type[BaseModel] | type[list]) -> type[BaseModel]:
    """
    Creates a response model for the iterative creation of objects. Allows the LLM to choose whether it needs to
    create another object, or stop. The output of this should be used as the `response_model` for the `completion` call

    :param obj: The object to be created
    :return: The response model
    """

    class CreateObjectOrStop(BaseModel):
        """Create another object or stop"""
        response: obj | StopObjectCreation = Field(..., description="Either the object to be created, "
                                                                    "or the StopObjectCreation signal object")

    return CreateObjectOrStop
```

In my specific use case, I'm using `response_model=create_object_or_stop(list[MyPyDanticModel])` and it failed. When I switched to `response_model=create_object_or_stop(List[MyPyDanticModel])` it worked. 

My `instructor` version is `1.4.3`

**Comment by ivanbelenky** [comment]
I tried to replicate you error on version `1.4.3`.  I failed to do so.

```python
class StopObjectCreation(BaseModel):
    ...

def create_object_or_stop(obj: type[BaseModel] | type[list]) -> type[BaseModel]:
    ...

client = instructor.from_openai(openai.OpenAI())


class User(BaseModel):
    name: str
    age: int


client.chat.completions.create(
    model='gpt-3.5-turbo',
    response_model=create_object_or_stop(list[User]), 
    messages =[{'role':'user', 'content':'Give me a couple of users'}]
)
```

Results are working as expected. I would suggest updating instructor, and marking this issue as closed, given that the problem does not appear to reside inside instructor. It may be a typo on your end. 

The traceback you posted is quite clear, `issubclass` is being called with a non type argument. If you cannot or don't want to upgrade, I suggest rooting this one out via logging your current env modules and check what object is landing at the `issubclass` call inside `instructor.function_calls`. Usually doing this narrows down the ownership of the bug, either your code or instructor in this case. If it were instructor, the above action would result in enough detail for replicability and posterior hf. I encourage this practice before submitting any issues.

**Comment by eliorc** [comment]
I don't know if it makes a difference, but I'm using `instructor_client = instructor.from_litellm(litellm.completion)`
I hope I'll have time this week to try upgrade and see if the error still persist, if so I'll update here.
Anyway, I have my own obligations and your tone is a bit aggresive with regards to what I should do - I do the best I can to contribute to open-source when I can, definitely was not lazy on this one

**Comment by ivanbelenky** [comment]
Hey @eliorc thanks for your reply and pointing out that you are using `litellm`. My bad for not clarifying. I saw the client you were using on the traceback, and tested as well for it. So, still not able to reproduce the error. Looking forward to your update.

**Comment by eliorc** [comment]
Well I'm running out of options, I don't have the availability to create a fully reproducable standalone example... 
The only thing I can think of that is different than your implementation is that my models are more complex than your `User` model, they are more complex, specifically they include reference to lists of other models for exmaple

```python
class User(BaseModel):
    name: str
    last_name: str
    friends: list[Friend]
```

because in this case I also changed the `list[Friends]` to `List[Friends]` 

hopefully this will uncover the bug I'm experiencing, if not I'll close this issue until I will have the availablity to create a reproducible example

**Comment by ivanbelenky** [comment]
```python
CreateObjectOrStop(response=[
    User(name='Alice', last_name='Smith', friends=[
        Friend(closeness=5.0, name='Bob', last_name='Johnson'), 
        Friend(closeness=3.0, name='Charlie', last_name='Brown')]
    ), 
    User(name='Eve', last_name='Taylor', friends=[
        Friend(closeness=4.0, name='Grace', last_name='Davis'), 
        Friend(closeness=2.0, name='Henry', last_name='Wilson')
    ])
])
```

Thanks @eliorc  for the clarification. Still failing to reproduce. Happy to check with more reproducible steps.

Cheers.

**Comment by eliorc** [comment]
I'm out of idea, I'm closing this and I'll reopen next time I'll be around this
