### ISSUE TITLE
passing API key as environment variable name?

### ISSUE THREAD

**Issue by DGoettlich** [instructor-ai/instructor#1118]
**Describe the bug**
I am trying to create a batch job and am passing the environment variable name with 

import config
client = instructor.from_openai(OpenAI(api_key=os.environ.get(config.api_keys.openai)),
                     mode=instructor.Mode.JSON)

When i run e.g., $instructor --help, it throws an error saying that the key has to be passed or an environment variable named OPENAI_API_KEY. We're trying to keep track of OpenAI usage across projects and have keys for different projects. is it not possible to pass the name of the env variable holding the API key?

**Comment by Flopsky** [comment]
Are you sure that `os.environ.get(config.api_keys.openai)` result is not None or empty str ? print it out, and let us know. (Don t send the result of the print here)

**Comment by ivanleomk** [comment]
@DGoettlich If you're running it with a script, you can pass it in without an issue to the api_key parameter for OpenAI.

If you're running it in the CLI you can also set it with something like

```
export VARIABLE_NAME="value"
```

This will override any existing configuration you have for that specific shell. Once you close/terminate it, then it will just revert back to your default settings.

Closing this issue for now but feel free to re-open if issue persists
