### ISSUE TITLE
Nested Optionals get ignored by the LLM

### ISSUE THREAD

**Issue by paulomtts** [instructor-ai/instructor#1124]
- [x] This is actually a bug report.
- [x] I am not getting good LLM Results
- [x] I have tried asking for help in the community on discord or discussions and have not received a response (I did get one, just not one that made much sense against my further investigation).
- [x] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [x] gpt-4
- [ ] Other (please specify)

**Describe the bug**
When a pydantic model has a property whose type is `Union[ModelA, ModelB]`, any properties typed `Optional` within either `ModelA` or `ModelB` are ignored by the LLM.

**To Reproduce**
```
class InterventionRequest(BaseModel):
    """
    Use when you want the user to intervene.
    """
    request: str


class Tool(BaseModel):
    """
    Use this tool to get users from the database.
    """
    order1: Optional[str] = Field(
        default=None,
        description="The order to sort the users by. Should be in format <field>:<order>, e.g.: 'field1:asc'. Can only include one order. Leave blank to return all users in no particular order.",
    )
    filter1: Optional[str] = Field(
        default=None,
        description="Use this when you want to filter based on a value. Format <field>:<operator>:<value>. Can only include multiple filters (comma separated). Example: 'email:ct:test@test.com,score:gte:50'. Operators: eq (equals), neq (not equals), ct (contains), nct (does not contain), stw (starts with), edw (ends with). Leave blank when not filtering by field value.",
    )
    fields: Optional[str] = Field(
        default=None,
        description="Use this to set the fields that will be returned. Should be in format <field1>,<field2>,<field3>. Can only include multiple fields (comma separated). Example: 'email,score'. Leave blank if you want to return all fields.",
    )
    count: Optional[int] = Field(
        default=None,
        description="The number of users to return. Maximum is 10_000.",
    )


class ToolCall(BaseModel):
    choice: Union[InterventionRequest, Tool] = Field(
        description="The choice of what to use. You can either request an intervention by the user, or use the tool."
    )
```

**Expected behavior**
The `Tool` would simply be filled as expected whenever we pass `ToolCall` as a `response_model`. What happens instead is that all fields whose type is `Optional` are consistently ignored.

**Extra notes**
I have been able to demonstrate that the issue is not with prompting or complexity of the pydantic model. I did:

![image](https://github.com/user-attachments/assets/290526e8-7b99-4c84-aa8a-688d429b362f)

And got:

![image](https://github.com/user-attachments/assets/1f9fe7cf-bfe9-4b83-9cf5-58698532728a)

Obviously, this is not a huge issue, as there is a workaround. I just wish it wouldn't ignore the Optionals, as that would make the writing more pythonic.

**Comment by ivanleomk** [comment]
Hmm I don't really get this problem tbh. I suspect either 

(1) the prompt itself doesn't provide enough information or clear instructions
(2) The model is being asked to generate a rather complex schema. You can honestly use pydantic to do post processing if you need the data in a specific format if it helps.

```
from typing import Optional, Union
from pydantic import BaseModel
from openai import OpenAI
import instructor

client = instructor.from_openai(OpenAI())


class GoogleSearch(BaseModel):
    user_query: str
    start_date: Optional[str] = None
    end_date: Optional[str] = None
    email_filters: Optional[list[str]] = None


class GetCalendar(BaseModel):
    relevent_emails: list[str]
    start_date: Optional[str] = None
    end_date: Optional[str] = None


class ModelChoice(BaseModel):
    steps: list[Union[GoogleSearch, GetCalendar]]


def generate_plan(query: str):
    return client.chat.completions.create(
        model="gpt-4o-mini",
        response_model=ModelChoice,
        messages=[
            {
                "role": "system",
                "content": "You are a helpful assistant that plans queries well. Today is 2024-11-08.",
            },
            {
                "role": "user",
                "content": query,
            },
        ],
    )


print(generate_plan("Go fetch my calendar for the next 6 days thanks"))
# steps=[GetCalendar(relevent_emails=['your_email@example.com'], start_date='2024-11-08', end_date='2024-11-14')]
print(generate_plan("Fetch my emails from jason@instructor.ai for the last 2 days"))
# steps=[GetCalendar(relevent_emails=['jason@instructor.ai'], start_date='2024-11-06', end_date='2024-11-08')]

```

Going to close this issue for now
