### ISSUE TITLE
`rust` installation requirement (re: jiter dependency)

### ISSUE THREAD

**Issue by aretrace** [instructor-ai/instructor#1139]
When I installed instructor (`uv add instructor`), I had to install the [rust toolchain](https://rustup.rs/) because of the `jiter=0.5.0` dependency. 

I haven't seen in the docs that compilation steps are required to install this package, is this expected installation behavior (or is it just my machine)?

**Comment by asvintheguy** [comment]
I am also just now running into this rust issue as well. Previously, I did not have to install rust to install instructor.

**Comment by ivanleomk** [comment]
@aretrace hmmm i haven't had this specific problem before, neither have I installed rust on the new development machine I'm using. 

How does the error message occur?

**Comment by aretrace** [comment]
@ivanleomk I've uninstalled Rust via `rustup self uninstall` trying to re-create the error but now the installation still works 😅.
The error occurred during  `uv add instructor`, it said it something like `Failed to build jiter, do you have the rust toolchain installed?`.

@asvintheguy perhaps you can still bring up the exact error message.

**Comment by r-dh** [comment]
I've ran into the same issue.

It should be fixed with https://github.com/pydantic/jiter/releases/tag/v0.6.1

Let's see if it is indeed fixed once the dependabot dependency #1151 bump is merged.

**Comment by ivanleomk** [comment]
@r-dh and @aretrace I just released a new version of 1.6.4 which has jiter bumped to 0.6.1. Could you try to give it a shot?

**Comment by ivanleomk** [comment]
Going to close this issue for now but feel free to re-open if it persists
