### ISSUE TITLE
create_partial streaming not behaving as expected (again)

### ISSUE THREAD

**Issue by KennyVaneetvelde** [instructor-ai/instructor#1147]
- [x] This is actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [x] I have tried searching the documentation and have not found an answer.

**What Model are you using?**
gpt-4o but it occurs on all models AFAIK

**Describe the bug**
I was following the docs, more specifically https://python.useinstructor.com/concepts/partial/#understanding-partial-responses and I noticed my output was behaving differently from the screenshot.

After a lot of trial & error I decided it must be a bug, and I did find this old bug report where someone was having the exact same issue: https://github.com/instructor-ai/instructor/issues/665

This was fixed, but, I am afraid the issue got re-introduced. With the code from the original bug report, I get the same bad output as originally described in the bug report

**To Reproduce**
```python
from pydantic import BaseModel, Field
from instructor import from_openai
from openai import OpenAI

class Summary(BaseModel):
    summary: str = Field(description="A detailed summary")

def main():
    client = from_openai(OpenAI())
    extraction_stream = client.chat.completions.create_partial(
        model="gpt-4o",
        response_model=Summary,
        messages=[
             {"role": "system", "content": "You summarize text"},
            {"role": "user", "content": " Summarize: Mary had a little lamb"}
        ],
        stream=True,
    )

    for extraction in extraction_stream:
        print(extraction)

main()
```

**Expected behavior**
I expect it to update token per token, not wait for everything to be done.

**Screenshots**
![image](https://github.com/user-attachments/assets/80f76985-57d9-4c51-9359-c86fd9569777)

**Comment by ivanleomk** [comment]
@KennyVaneetvelde this is less of a bug but more towards how we've chosen to process partial json objects with jiter. If we process it token by token here, it breaks support for literals. 

Going to just close the issue in light of this for now

**Comment by KennyVaneetvelde** [comment]
@ivanleomk hmm darnit, I understand, but is there any workaround or any direction you can point me in to contribute being able to toggle this somehow? Or could we improve Instructor so it can even maybe apply only to specific properties?

I really need it for a more chat-based application - my use case is, for example: A support assistant, a message from the AI can either be:
- a ChatMessage which has a property "message" which I really need streaming on, and a property "followup_questions" which I don't care if they stream...
- an AppointmentResponse that books an appointment, where I also don't care about streaming that much.

Not having the streaming capabilities really breaks a lot of use cases for me :-\

**Comment by ivanleomk** [comment]
@KennyVaneetvelde had a bit more time to look at it, what are your thoughts about something like this?

#1152 

This turns on trailing strings by default ( allowiung you to stream character by character ) and you can disable it by importing a specific mixing

**Comment by KennyVaneetvelde** [comment]
@ivanleomk looks acceptable to me but I do wonder, is there a way to make it more dynamic, perhaps by deferring parsing the literals until later by dynamically removing them & re-adding them to the partial schema.. or would this have downsides/introduce too much complexity/just be impossible?

Either way, it is still much better than not having trailing strings or having to monkeypatch the functionality back in as I did now as a temp workaround!

**Comment by ivanleomk** [comment]
@KennyVaneetvelde I've just released this in 1.6.4

```
from pydantic import BaseModel
from instructor.dsl.partial import PartialLiteralMixin
import openai
import instructor


class LiteralUser(BaseModel, PartialLiteralMixin):
    name: str
    age: int


class User(BaseModel):
    name: str
    age: int


client = instructor.from_openai(openai.OpenAI())

resp = client.chat.completions.create_partial(
    model="gpt-4o-mini",
    messages=[{"role": "user", "content": "Ivan Leo is 27 and lives in Singapore"}],
    response_model=LiteralUser,
)

for r in resp:
    print(r)
# name=None age=None
# name='Ivan Leo' age=None
# name='Ivan Leo' age=27

resp = client.chat.completions.create_partial(
    model="gpt-4o-mini",
    messages=[{"role": "user", "content": "Ivan Leo is 27 and lives in Singapore"}],
    response_model=User,
)

for r in resp:
    print(r)

# name='' age=None
# name='Ivan' age=None
# name='Ivan Leo' age=None
# name='Ivan Leo' age=27

```

Let me know if this works for you! :)

**Comment by KennyVaneetvelde** [comment]
@ivanleomk Magnificent!

**Comment by yanqianglu** [comment]
hi @ivanleomk , I think the partial streaming is still not working as expected. See this example

```python
import logging

import instructor
from anthropic import Anthropic
from pydantic import BaseModel

# Configure logging
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

# Define the API key
ANTHROPIC_API_KEY = "xxx"


# Define the response model with two fields
class StreamingResponse(BaseModel):
    short_output: str
    long_output: str


# Create an Anthropic client
anthropic_client = Anthropic(api_key=ANTHROPIC_API_KEY)

# Create an instructor client for Claude
instructor_client = instructor.from_anthropic(client=anthropic_client)


# Function to test partial streaming
def test_partial_streaming():
    # Define the prompt
    prompt = """
    Please provide:
    1. A short sentence as the short_output
    2. A long sentence repeated 25 times as the long_output
    """

    # Use instructor to get a streaming response
    response = instructor_client.messages.create_partial(
        model="claude-3-opus-20240229",
        max_tokens=1000,
        messages=[{"role": "user", "content": prompt}],
        response_model=StreamingResponse,
        stream=True,
    )

    for chunk in response:
        # Print the raw chunk for debugging
        logger.info(f"Chunk: {chunk}")


if __name__ == "__main__":
    test_partial_streaming()

```


```bash
2025-04-09 15:15:42,351 - INFO - HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2025-04-09 15:15:42,352 - INFO - Streaming response:
2025-04-09 15:15:43,144 - INFO - Chunk: short_output=None long_output=None
2025-04-09 15:15:43,145 - INFO - Chunk: short_output=None long_output=None
2025-04-09 15:15:43,147 - INFO - Chunk: short_output='This is a' long_output=None
2025-04-09 15:15:43,147 - INFO - Chunk: short_output='This is a short outpu' long_output=None
2025-04-09 15:15:43,147 - INFO - Chunk: short_output='This is a short output se' long_output=None
2025-04-09 15:15:43,147 - INFO - Chunk: short_output='This is a short output sentence.' long_output=None
2025-04-09 15:15:55,745 - INFO - Chunk: short_output='This is a short output sentence.' long_output=None
2025-04-09 15:15:55,754 - INFO - Chunk: short_output='This is a short output sentence.' long_output=None
2025-04-09 15:15:55,754 - INFO - Chunk: short_output='This is a short output sentence.' long_output=None
2025-04-09 15:15:55,754 - INFO - Chunk: short_output='This is a short output sentence.' long_output='T'
2025-04-09 15:15:55,754 - INFO - Chunk: short_output='This is a short output sentence.' long_output='This is a l'
2025-04-09 15:15:55,754 - INFO - Chunk: short_output='This is a short output sentence.' long_output='This is a long o'
2025-04-09 15:15:55,754 - INFO - Chunk: short_output='This is a short output sentence.' long_output='This is a long outp'
2025-04-09 15:15:55,754 - INFO - Chunk: short_output='This is a short output sentence.' long_output='This is a long output'
....
....
<omit the intermediate result, and the last result is the following>
2025-04-09 15:15:55,956 - INFO - Chunk: short_output='This is a short.......long output sentence that will be repeated 25 times.'
```

As you can see from the timestamp,  there is a 12 seconds gap from the end of `short_output` and the beginning of `long_output`, and all the streaming chunks of `long_output` are all within a second. So it's basically a fake streaming for `long_output`, the program waited until the long_output was finished, then dump them out as a stream.
