### ISSUE TITLE
Issue with Gemini on Vertex AI

### ISSUE THREAD

**Issue by sandeep540** [instructor-ai/instructor#1166]
- [ x] This is actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [ ] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [x ] Other (gemini-1.5-pro-002 on vertex ai)

**Describe the bug**
When executing this example - https://python.useinstructor.com/hub/vertexai/#vertex-ai-client , I am getting
`ModuleNotFoundError: No module named 'instructor.client_vertexai'; 'instructor' is not a package
`
**StackTrace**
`Traceback (most recent call last):
  File "c:\Users\A0100109\python\gemini-bq-py-test\instructor.py", line 1, in <module>
    import instructor.client_vertexai  as instructor
  File "c:\Users\A0100109\python\gemini-bq-py-test\instructor.py", line 1, in <module>
    import instructor.client_vertexai  as instructor
ModuleNotFoundError: No module named 'instructor.client_vertexai'; 'instructor' is not a package`

**To Reproduce**
Here is Code I used
  ```
import instructor
  
  from pydantic import BaseModel
  import vertexai.generative_models as GenerativeModel
  import vertexai
  
  vertexai.init(project="XXXX", location="us-central1")
  client = GenerativeModel.GenerativeModel("gemini-1.5-pro-002")
  client = instructor.from_vertexai(client)
  
  
  class UserDetails(BaseModel):
      name: str
      age: int
  
  resp = client.create(
      response_model=UserDetails,
      messages=[
          {
              "role": "user",
              "content": f'Extract the following entities: "Jason is 20"',
          },
      ],
  )
  print(resp)
```
**REQUIREMENTS.TXT
```
google-cloud-aiplatform==1.71.1
pydantic==2.9.2
instructor==1.6.3
jsonref==1.1.0
```

**Expected behavior**
Error should not appear 

**Screenshots**

**Comment by ivanleomk** [comment]
Could you try installing and re-installing instructor.

**Comment by ivanleomk** [comment]
> Tried, Different error
> 
> ```
> $ c:/Users/A0100109/python/gemini-bq-py-test/.venv/Scripts/python.exe c:/Users/A0100109/python/gemini-bq-py-test/instructor.py
> Traceback (most recent call last):
>   File "c:\Users\A0100109\python\gemini-bq-py-test\instructor.py", line 1, in <module>
>     import instructor
>   File "c:\Users\A0100109\python\gemini-bq-py-test\instructor.py", line 12, in <module>
>     client = instructor.from_vertexai(client)
>              ^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: partially initialized module 'instructor' has no attribute 'from_vertexai' (most likely due to a circular import)
> (.venv) 
> ```

Could you try renaming your script to another name? It seems like you're running it from a script called `instructor.py`

**Comment by sandeep540** [comment]
Worked @ivanleomk , Kind of mistake from my side having same name as package for file

![Screenshot 2024-11-12 at 4 00 39 PM](https://github.com/user-attachments/assets/bf5a12e6-0baa-4d02-98d1-169a074c9004)

**Comment by ivanleomk** [comment]
Awesome glad to hear that
