### ISSUE TITLE
jsonref missing from requirements.txt

### ISSUE THREAD

**Issue by davesyms** [instructor-ai/instructor#1183]
- [X] This is actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [ ] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [ ] Other (please specify)
- [X ] Not Relevant

**Describe the bug**
client_vertexai.py imports jsonref on line 9. jsonref is not included in the requirements.txt

**To Reproduce**
If jsonref has not been installed on the venv running instructor.from_vertexai will result in a `ValueError - instructor has no attribute from_vertexai`. If directly importing: `from instructor.client_vertexai import from_vertexai` a module not found exception is thrown.

**Expected behavior**
For jsonref to be included in the requirements.txt.

**Comment by davesyms** [comment]
Fixed in PR: https://github.com/instructor-ai/instructor/pull/1184

**Comment by ivanleomk** [comment]
Closing this issue since it's resolved
